fix: Add missing f string in swiftcov func of xcode plugin (#96)
Fixes code coverage generation for some swift projects, currently looks
like this:

```sh
==> Running upload-coverage
      ./codecov  upload-coverage -t <redacted> --git-service github --gcov-executable gcov
info - 2025-09-18 21:10:08,461 -- ci service found: github-actions
info - 2025-09-18 21:10:08,620 -- Running swift coverage on the following list of files: --- {"matched_paths": ["/Users/runner/Library/Developer/Xcode/DerivedData/ChromaSwift-gtzsdaclinjizxegjyiqrvlbelap/Build/ProfileData/2823e84cf20da531196b91b0539218db7086d1c7/Coverage.profdata"]}
info - 2025-09-18 21:10:08,625 -- + Building reports for CChromaprintTests xctest
error: failed to load coverage: '/Users/runner/Library/Developer/Xcode/DerivedData/ChromaSwift-gtzsdaclinjizxegjyiqrvlbelap/Build/Products/Debug/CChromaprintTests.xctest/Contents/MacOS/{proj}': No such file or directory
warning - 2025-09-18 21:10:09,877 -- llvm-cov failed to produce results for /Users/runner/Library/Developer/Xcode/DerivedData/ChromaSwift-gtzsdaclinjizxegjyiqrvlbelap/Build/Products/Debug/CChromaprintTests.xctest/Contents/MacOS/{proj}
```